[package]
name = "pallet-evm-precompile-modexp"
version = "2.0.0-dev"
license = "Apache-2.0"
edition = "2021"
description = "MODEXP precompiles for EVM pallet."
 
[dependencies]
num = { version = "0.4", default-features = false, features = ["alloc"] }
# Frontier
fp-evm = { version = "3.0.0-dev", path = "../../../../primitives/evm", default-features = false }

[dev-dependencies]
hex = "0.4.3"
# Frontier
pallet-evm-test-vector-support = { version = "1.0.0-dev",git = "ssh://git@github.com/5ire-tech/5ire-substrate.git", branch = "QA", default-features = false  }

[features]
default = ["std"]
std = [
	"num/std",
	# Frontier
	"fp-evm/std",
]
