[package]
name = "pallet-session-benchmarking"
version = "4.0.0-dev"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME sessions pallet benchmarking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.9", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["std_rng"] }
frame-benchmarking = { workspace = true}
frame-support = { workspace = true}
frame-system = { workspace = true}
pallet-session = { path = "..", default-features = false}
pallet-staking = { workspace = true}
sp-runtime = { workspace = true}
sp-session = { workspace = true}
sp-std = { workspace = true}

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "3.6.9", features = ["derive"] }
scale-info = "2.1.1"
frame-election-provider-support = { workspace = true }
pallet-balances = { workspace = true }
pallet-timestamp = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }

[features]
default = [ "std" ]
std = [
	"frame-benchmarking/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-timestamp/std",
	"rand/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
