[package]
name = "fp-self-contained"
version = "1.0.0-dev"
license = "Apache-2.0"
edition = "2021"
description = "Primitive Ethereum abstractions for Substrate."
 
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
scale-codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }
 serde = { version = "1.0",optional = true, features = ["derive"] }
# Substrate
frame-support = { version = "4.0.0-dev",git = "ssh://git@github.com/5ire-tech/5ire-substrate.git", branch = "new_Evm_rpc", default-features = false  }
sp-runtime = { version = "7.0.0",git = "ssh://git@github.com/5ire-tech/5ire-substrate.git", branch = "new_Evm_rpc", default-features = false }

[features]
default = ["std"]
std = [
	"scale-codec/std",
	"scale-info/std",
	"serde",
	# Substrate
	"frame-support/std",
	"sp-runtime/std",
]
try-runtime = [
	"sp-runtime/try-runtime",
]
