[package]
name = "pallet-evm-precompile-simple"
version = "2.0.0-dev"
license = "Apache-2.0"
edition = "2021"
description = "Simple precompiles for EVM pallet."

[dependencies]
ripemd = { version = "0.1", default-features = false }
# Substrate
sp-io = { version = "7.0.0",git = "ssh://git@github.com/5ire-tech/5ire-substrate.git", branch = "upgrade/5irechain-V0.1", default-features = false }
# Frontier
fp-evm = { version = "3.0.0-dev", path = "../../../../primitives/evm", default-features = false }
#fp-evm = { version = "3.0.0-dev",  git = "ssh://git@github.com/5ire-tech/5ire-substrate.git", branch = "upgrade/5irechain-V0.1", default-features = false }

[dev-dependencies]
pallet-evm-test-vector-support = { version = "1.0.0-dev",  path = "../../../../frame/evm/test-vector-support",  default-features = false }
# Frontier

[features]
default = ["std"]
std = [
	"ripemd/std",
	# Substrate
	"sp-io/std",
	# Frontier
	"fp-evm/std",
	"pallet-evm-test-vector-support/std"
]
