[package]
name = "pallet-transaction-payment-rpc"
version = "4.0.0-dev"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "RPC interface for the transaction payment pallet."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.12" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
pallet-transaction-payment-rpc-runtime-api = { path = "runtime-api" }
sp-api = {workspace = true }
sp-blockchain = { workspace = true }
sp-core = { workspace = true }
sp-rpc = { workspace = true}
sp-runtime = { workspace = true }
sp-weights = { workspace = true }
