[package]
name = "pallet-evm-precompile-ed25519"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "ED25519 precompiles for EVM pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
ed25519-dalek = { version = "2.1.0", default-features = false, features = ["alloc"] }
# Frontier
fp-evm = { workspace = true }

[features]
default = ["std"]
std = [
	# Frontier
	"fp-evm/std",
]
