[package]
name = "fp-storage"
version = "2.0.0"
license = "Apache-2.0"
edition = "2021"
description = "Storage primitives for Ethereum RPC (web3) compatibility layer for Substrate."
 
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false, features = ["derive"] }
serde = { version = "1.0",optional = true, features = ["derive"] }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde",
]
