[package]
name = "firechain-runtime-core-primitives"
version = "0.1.0"
authors = ["5ire Team <admin@5ire.org>"]
description = "Runtime core primitive"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-runtime = { workspace = true }
node-primitives = { workspace = true }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"node-primitives/std"
]
