[package]
name = "firechain-runtime-core-primitives"
version = "0.1.0"
authors = ["5ire Team <admin@5ire.org>"]
description = "Runtime core primitive"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-runtime = { version = "24.0.0", default-features = false, git = "ssh://git@github.com/5ire-tech/5ire-substrate.git", branch = "polkadot-v1.1.0" }
node-primitives = { version = "2.0.0", default-features = false, git = "ssh://git@github.com/5ire-tech/5ire-substrate.git", branch = "polkadot-v1.1.0" }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"node-primitives/std"
]
