[package]
name = "firechain-runtime-core-primitives"
version = "1.0.0"
authors = ["5ire Team <admin@5ire.org>"]
description = "Runtime core primitive"
edition = "2021"


[dependencies]
sp-runtime = { workspace = true }
node-primitives = { workspace = true }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"node-primitives/std"
]
