[package]
name = "pallet-evm-test-vector-support"
version = "1.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Test vector support for EVM pallet."
repository = "https://github.com/paritytech/frontier/"

[dependencies]
evm = { git = "https://github.com/rust-blockchain/evm", rev = "01bcbd2205a212c34451d3b4fabc962793b057d3", features = ["with-codec"] }
hex = "0.4.3"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0"

# Substrate
sp-core = { version = "6.0.0", git = "https://github.com/5ire-tech/5ire-substrate.git", branch = "master", default-features = false }

# Frontier
fp-evm = { version = "3.0.0-dev", path = "../../../primitives/evm", default-features = false }
